### ISSUE TITLE
Value of 'r'

### ISSUE THREAD

**Issue by chandagrover** [dogehhh/ReCLIP#9]
When I ran below code on custom dataset,
**python tools/pseudo_class.py --cfg 'config/xxx_train_ori_cfg.yaml' --model 'RECLIPPP',** 

I got below error:

ReCLIPPP(train_images, train_labels, cfg, window_size=(w, w), step_size=r)
NameError: name 'r' is not defined

what value should I provide to step_size in the variable 'r'?

**Comment by dogehhh** [comment]
Sorry, relevant code has been corrected.
